using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace StellarFramework.Editor
{
    /// <summary>
    /// Generates a backend-neutral map of stable project asset paths.
    /// The generated constants deliberately use standard Assets/... paths so the same key can be
    /// consumed by AssetBundle, Addressables and YooAsset; ResourceLoader normalizes Resources paths.
    /// </summary>
    public static class AssetsMapGenerator
    {
        public const string OutputAssetPath = "Assets/StellarFramework/Generated/AssetMap/AssetsMap.cs";
        private const string HotUpdatePublisherPayloadRoot = "Assets/HotUpdatePublisherConsumerE2E/Generated";

        private static readonly HashSet<string> ExcludedExtensions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            ".cs", ".asmdef", ".asmref", ".meta", ".dll", ".pdb", ".mdb", ".md", ".unitypackage"
        };

        private static readonly HashSet<string> CSharpKeywords = new HashSet<string>(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach",
            "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock", "long",
            "namespace", "new", "null", "object", "operator", "out", "override", "params", "private",
            "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof",
            "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true", "try", "typeof",
            "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
        };

        public static void GenerateAndLog()
        {
            bool changed = GenerateIfNeeded();
            Debug.Log(changed
                ? $"[AssetsMapGenerator] Updated {OutputAssetPath}."
                : $"[AssetsMapGenerator] {OutputAssetPath} is already up to date.");
        }

        /// <summary>
        /// Regenerates only when content actually changed, preventing import/compile loops.
        /// </summary>
        public static bool GenerateIfNeeded()
        {
            string code = BuildSource(CollectRuntimeAssetPaths());
            string absolutePath = ToAbsolutePath(OutputAssetPath);
            string existing = File.Exists(absolutePath) ? File.ReadAllText(absolutePath, Encoding.UTF8) : null;
            if (string.Equals(NormalizeLineEndings(existing), NormalizeLineEndings(code), StringComparison.Ordinal))
            {
                return false;
            }

            string directory = Path.GetDirectoryName(absolutePath);
            if (!string.IsNullOrWhiteSpace(directory)) Directory.CreateDirectory(directory);
            File.WriteAllText(absolutePath, code, new UTF8Encoding(false));
            AssetDatabase.ImportAsset(OutputAssetPath, ImportAssetOptions.ForceUpdate);
            return true;
        }

        internal static IReadOnlyList<string> CollectRuntimeAssetPaths()
        {
            string[] guids = AssetDatabase.FindAssets(string.Empty, new[] { "Assets" });
            var paths = new List<string>(guids.Length);
            for (int i = 0; i < guids.Length; i++)
            {
                string path = AssetDatabase.GUIDToAssetPath(guids[i]).Replace('\\', '/');
                if (ShouldInclude(path)) paths.Add(path);
            }

            paths.Sort(StringComparer.Ordinal);
            return paths;
        }

        internal static string BuildSource(IReadOnlyList<string> assetPaths)
        {
            var root = new FolderNode("Assets");
            for (int i = 0; i < assetPaths.Count; i++)
            {
                AddAsset(root, assetPaths[i]);
            }

            var sb = new StringBuilder(Math.Max(4096, assetPaths.Count * 96));
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by StellarFramework ResKit AssetsMapGenerator. Do not edit manually.");
            sb.AppendLine("// Values are canonical Unity Assets/... paths and are backend-neutral resource keys.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace StellarFramework.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class AssetsMap");
            sb.AppendLine("    {");
            EmitNodeContents(sb, root, 2, "AssetsMap");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static bool ShouldInclude(string path)
        {
            if (!MayAffectGeneratedMap(path)) return false;
            if (AssetDatabase.IsValidFolder(path)) return false;

            Type mainType = AssetDatabase.GetMainAssetTypeAtPath(path);
            if (mainType == null || mainType == typeof(MonoScript) || mainType == typeof(DefaultAsset)) return false;
            return true;
        }

        public static bool MayAffectGeneratedMap(string path)
        {
            if (string.IsNullOrWhiteSpace(path)) return false;
            path = path.Replace('\\', '/');
            if (!path.StartsWith("Assets/", StringComparison.Ordinal)) return false;
            if (string.Equals(path, OutputAssetPath, StringComparison.Ordinal)) return false;
            if (string.Equals(path, HotUpdatePublisherPayloadRoot, StringComparison.Ordinal) ||
                path.StartsWith(HotUpdatePublisherPayloadRoot + "/", StringComparison.Ordinal)) return false;
            if (path.StartsWith("Assets/AddressableAssetsData/", StringComparison.Ordinal)) return false;
            if (path.StartsWith("Assets/HybridCLRGenerate/", StringComparison.Ordinal)) return false;
            if (path.StartsWith("Assets/StellarFrameworkVerification/", StringComparison.Ordinal)) return false;
            if (path.StartsWith("Assets/StellarFrameworkBootstrap/", StringComparison.Ordinal)) return false;
            if (path.StartsWith("Assets/StreamingAssets/", StringComparison.Ordinal)) return false;
            if (path.StartsWith("Assets/docs/", StringComparison.OrdinalIgnoreCase)) return false;
            if (path.StartsWith("Assets/Temp/", StringComparison.OrdinalIgnoreCase)) return false;
            if (path.StartsWith("Assets/__StellarTempRecovery/", StringComparison.Ordinal)) return false;
            if (path.StartsWith("Assets/Screenshots/", StringComparison.Ordinal)) return false;
            if (path.IndexOf("/Editor/", StringComparison.OrdinalIgnoreCase) >= 0) return false;
            if (path.IndexOf("/Tests/", StringComparison.OrdinalIgnoreCase) >= 0) return false;
            if (path.IndexOf("/FrameworkDoc/", StringComparison.OrdinalIgnoreCase) >= 0) return false;
            if (Path.GetFileName(path).StartsWith("InitTestScene", StringComparison.OrdinalIgnoreCase)) return false;

            string extension = Path.GetExtension(path);
            return !ExcludedExtensions.Contains(extension);
        }

        private static void AddAsset(FolderNode root, string assetPath)
        {
            string[] segments = assetPath.Split('/');
            if (segments.Length < 2) return;

            FolderNode node = root;
            for (int i = 1; i < segments.Length - 1; i++)
            {
                string raw = segments[i];
                if (!node.Children.TryGetValue(raw, out FolderNode child))
                {
                    child = new FolderNode(raw);
                    node.Children.Add(raw, child);
                }
                node = child;
            }

            string fileName = segments[segments.Length - 1];
            node.Assets.Add(new AssetEntry(fileName, assetPath));
        }

        private static void EmitNodeContents(
            StringBuilder sb,
            FolderNode node,
            int indentLevel,
            string enclosingTypeName)
        {
            string indent = new string(' ', indentLevel * 4);
            Dictionary<string, string> childNames = ResolveNames(node.Children.Keys);
            EnsureChildTypeNamesDoNotMatchEnclosingType(childNames, enclosingTypeName);
            var reserved = new HashSet<string>(childNames.Values, StringComparer.Ordinal)
            {
                enclosingTypeName
            };

            foreach (AssetEntry asset in node.Assets.OrderBy(entry => entry.Path, StringComparer.Ordinal))
            {
                string baseName = Path.GetFileNameWithoutExtension(asset.FileName);
                string memberName = SanitizeIdentifier(baseName, "Asset");
                if (reserved.Contains(memberName) || node.Assets.Count(other =>
                        string.Equals(SanitizeIdentifier(Path.GetFileNameWithoutExtension(other.FileName), "Asset"), memberName, StringComparison.Ordinal)) > 1)
                {
                    string extension = Path.GetExtension(asset.FileName).TrimStart('.');
                    memberName = memberName + "_" + SanitizeIdentifier(extension, "Asset");
                }

                if (!reserved.Add(memberName))
                {
                    memberName += "_" + StableHash(asset.Path);
                    reserved.Add(memberName);
                }

                sb.Append(indent)
                    .Append("public const string ")
                    .Append(memberName)
                    .Append(" = \"")
                    .Append(EscapeString(asset.Path))
                    .AppendLine("\";");
            }

            foreach (KeyValuePair<string, FolderNode> pair in node.Children.OrderBy(pair => pair.Key, StringComparer.Ordinal))
            {
                string className = childNames[pair.Key];
                sb.AppendLine();
                sb.Append(indent).Append("public static class ").AppendLine(className);
                sb.Append(indent).AppendLine("{");
                EmitNodeContents(sb, pair.Value, indentLevel + 1, className);
                sb.Append(indent).AppendLine("}");
            }
        }

        private static void EnsureChildTypeNamesDoNotMatchEnclosingType(
            Dictionary<string, string> childNames,
            string enclosingTypeName)
        {
            if (childNames == null || string.IsNullOrWhiteSpace(enclosingTypeName))
            {
                return;
            }

            var used = new HashSet<string>(childNames.Values, StringComparer.Ordinal);
            foreach (string rawName in childNames.Keys.OrderBy(value => value, StringComparer.Ordinal).ToArray())
            {
                string candidate = childNames[rawName];
                if (!string.Equals(candidate, enclosingTypeName, StringComparison.Ordinal))
                {
                    continue;
                }

                used.Remove(candidate);
                string renamed = candidate + "_Folder";
                if (string.Equals(renamed, enclosingTypeName, StringComparison.Ordinal) || used.Contains(renamed))
                {
                    renamed = candidate + "_" + StableHash(rawName);
                }
                while (used.Contains(renamed))
                {
                    renamed += "_" + StableHash(rawName + renamed);
                }

                childNames[rawName] = renamed;
                used.Add(renamed);
            }
        }

        private static Dictionary<string, string> ResolveNames(IEnumerable<string> rawNames)
        {
            string[] names = rawNames.OrderBy(value => value, StringComparer.Ordinal).ToArray();
            var result = new Dictionary<string, string>(StringComparer.Ordinal);
            var groups = names.GroupBy(value => SanitizeIdentifier(value, "Folder"), StringComparer.Ordinal);
            foreach (IGrouping<string, string> group in groups)
            {
                string[] values = group.ToArray();
                for (int i = 0; i < values.Length; i++)
                {
                    result[values[i]] = values.Length == 1
                        ? group.Key
                        : group.Key + "_" + StableHash(values[i]);
                }
            }
            return result;
        }

        private static string SanitizeIdentifier(string value, string fallback)
        {
            if (string.IsNullOrWhiteSpace(value)) return fallback;

            var sb = new StringBuilder(value.Length + 2);
            for (int i = 0; i < value.Length; i++)
            {
                char c = value[i];
                if (char.IsLetterOrDigit(c) || c == '_') sb.Append(c);
                else sb.Append('_');
            }

            string result = sb.ToString().Trim('_');
            if (string.IsNullOrEmpty(result)) result = fallback;
            if (!char.IsLetter(result[0]) && result[0] != '_') result = "_" + result;
            if (CSharpKeywords.Contains(result)) result = "_" + result;
            return result;
        }

        private static string StableHash(string value)
        {
            unchecked
            {
                uint hash = 2166136261;
                for (int i = 0; i < value.Length; i++)
                {
                    hash ^= value[i];
                    hash *= 16777619;
                }
                return hash.ToString("x8").Substring(0, 6);
            }
        }

        private static string EscapeString(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string ToAbsolutePath(string assetPath)
        {
            string projectRoot = Directory.GetParent(Application.dataPath)?.FullName ?? Application.dataPath;
            return Path.Combine(projectRoot, assetPath.Replace('/', Path.DirectorySeparatorChar));
        }

        private static string NormalizeLineEndings(string value)
        {
            return value?.Replace("\r\n", "\n");
        }

        private sealed class FolderNode
        {
            public readonly string RawName;
            public readonly Dictionary<string, FolderNode> Children = new Dictionary<string, FolderNode>(StringComparer.Ordinal);
            public readonly List<AssetEntry> Assets = new List<AssetEntry>();

            public FolderNode(string rawName)
            {
                RawName = rawName;
            }
        }

        private readonly struct AssetEntry
        {
            public readonly string FileName;
            public readonly string Path;

            public AssetEntry(string fileName, string path)
            {
                FileName = fileName;
                Path = path;
            }
        }
    }

    /// <summary>
    /// Keeps AssetsMap current without rewriting the file when unrelated imports occur.
    /// </summary>
    internal sealed class AssetsMapAutoGenerator : AssetPostprocessor
    {
        private static bool _scheduled;

        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths)
        {
            if (!ContainsRelevantChange(importedAssets) &&
                !ContainsRelevantChange(deletedAssets) &&
                !ContainsRelevantChange(movedAssets) &&
                !ContainsRelevantChange(movedFromAssetPaths))
            {
                return;
            }

            if (_scheduled) return;
            _scheduled = true;
            EditorApplication.delayCall += GenerateDelayed;
        }

        private static void GenerateDelayed()
        {
            _scheduled = false;
            if (EditorApplication.isCompiling || EditorApplication.isUpdating)
            {
                _scheduled = true;
                EditorApplication.delayCall += GenerateDelayed;
                return;
            }

            AssetsMapGenerator.GenerateIfNeeded();
        }

        private static bool ContainsRelevantChange(string[] paths)
        {
            if (paths == null) return false;
            for (int i = 0; i < paths.Length; i++)
            {
                string path = paths[i]?.Replace('\\', '/');
                if (string.IsNullOrWhiteSpace(path)) continue;
                if (AssetsMapGenerator.MayAffectGeneratedMap(path)) return true;
            }
            return false;
        }
    }
}
